PREFIX : <http://vocab.acdh/defc2cidoc#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX cidoc-crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?site  ?sitename_uri ?sitename
WHERE {
	?site a cidoc-crm:E7_Activity;
                cidoc-crm:P1_is_identified_by ?sitename_uri;
        ?site_name_uri cidoc-crm:P90_has_value ?sitename.
	
	
}